name: challenge

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Get current date as environment variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Get current date as environment variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Get current date as environment variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
    - name: Get current date as environment variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW
